<Project Sdk="Microsoft.NET.Sdk">
	<Project Sdk="Microsoft.NET.Sdk">
		<PropertyGroup>
			<TargetFramework>net8.0</TargetFramework>
			<RootNamespace>Orderly.Domain</RootNamespace>
			<AssemblyName>Orderly.Domain</AssemblyName>
		</PropertyGroup>
	</Project>


	<ItemGroup>
		<ProjectReference Include="..\Orderly.Application\Orderly.Application.csproj" />
		<ProjectReference Include="..\Orderly.Infrastructure\Orderly.Infrastructure.csproj" />
	</ItemGroup>

</Project>

